apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: django-rest
  region: us-east-1

nodeGroups:
  - name: ng-1
    labels: { role: api }
    instanceType: t2.medium
    desiredCapacity: 1
    volumeSize: 80
    ssh:
      allow: true # will use ~/.ssh/id_rsa.pub as the default ssh key